### ISSUE TITLE
Vorbereitung

### ISSUE THREAD

**Issue by flycam** [flycam/yaufs#3]
1) Materialien aus Uebung durchlesen
2) Fuse Beispielprojekt durchlesen
3) Vorgegebenen Code & Einstiegspunkte eingeben

**Comment by allothernamesaretaken** [comment]
Folgende Dateien müssen angepasst werden:
mkfs.myfs.cpp -> main funktion nimmt dateien entgegen und erstellt ein fs
myfs.cpp -> fuse operationen implementieren
alle anderen dinge können in eine extra datein geschrieben werden und dann in mkfs.myfs.cpp / myfs.cpp eingebunden werden.
